# Anaconda ISO installer configuration

# Kickstart commands for the installer
[customizations.installer.kickstart]
contents = """
# Use graphical installer
graphical

# Reboot after install
reboot
"""

# Enable all interactive screens
[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Storage"
]
